import { Toaster } from "sonner";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "./globals.css";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider>
          <SessionProvider session={session}>
            {children}
            <Toaster richColors closeButton duration={2000} />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
